manifest:
  remotes:
    - name: preacher325
      url-base: https://github.com/preacher325
  projects:
    - name: preacher325
      remote: zmk_pimoroni
      revision: soflergbtest
      import: app/west.yml
  self:
    path: config
